version: '2'
services:
    mtabd-app:
        image: mtabd
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://mtabd-postgresql:5432/mtabd
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mtabd-postgresql:
        extends:
            file: postgresql.yml
            service: mtabd-postgresql
